FROM python:3.7-slim-buster

MAINTAINER Amazigh "amazigh@insim.to"

WORKDIR /my1stchatbot
COPY mychatbot_amazigh.py /my1stchatbot

RUN apt update && apt install -y python3-pip
COPY . ./
RUN pip3 install nltk --no-cache-dir

#EXPOSE 8080

ENTRYPOINT [ "python3.7", "./mychatbot_amazigh.py" ]
